### ISSUE TITLE
Test messages are sent but check-in or messages are not

### ISSUE THREAD

**Issue by florianwgnr** [jhonderson/gone-man-switch#1]
I just started your application via docker-compose, added SMTP and telegram (test-messages are working for both) and setup a message to be sent after 2 days of not checking in, while sending the check-in notification after 1 day. 

![grafik](https://github.com/jhonderson/gone-man-switch/assets/39341393/4007b738-b480-403e-bc47-8313aeb22fd8)

This container is running since 2 days but i did not receive a message or can see anything in the logs. What is missing here?

![grafik](https://github.com/jhonderson/gone-man-switch/assets/39341393/23f00ee6-5f6b-44cf-b87d-1ca80559584e)

My setup:
- User SMTP + Telegram
- System SMTP
- Docker via docker-compose

**Comment by jhonderson** [comment]
Hello. It seems to me that you need to wait 3 days. 1 for the checkin to trigger, and 2 for the message to be sent, since message is delivered 2 days after the checkin notification is sent and not responded.

One more thing to keep in mind is that every time you interact with the website (I.e you open the website while logged in), the system will interprete that as you being available and will mark your checkin notifications as acknowledged. So for this test to work you will need to not interact with the website for 3+ days. Let me know how it goes.

**Comment by jhonderson** [comment]
Feel free to re-open if you are still having issues

**Comment by florianwgnr** [comment]
> Hello. It seems to me that you need to wait 3 days. 1 for the checkin to trigger, and 2 for the message to be sent, since message is delivered 2 days after the checkin notification is sent and not responded.
> 
> One more thing to keep in mind is that every time you interact with the website (I.e you open the website while logged in), the system will interprete that as you being available and will mark your checkin notifications as acknowledged. So for this test to work you will need to not interact with the website for 3+ days. Let me know how it goes.

Hi, thanks for your reply! The message has been delivered after a few days and i am quite happy with it. But since i was wondering when the messages arrive, maybe others will wonder too. 
What do you think about adding a "last check-in" date/time and a "next notification sent on" date/time? 

Hi, thank you for your reply! The message has been delivered delivered after a few days and I am quite happy with your application. But since i was wondering when the messages arrive, maybe others will wonder too. What do you think about adding a "last check-in" date/time and a "next notification sent on" date/time? This will make it clear to everyone when the notifications will be sent, especially after logging in (which checks the user in).

**Comment by jhonderson** [comment]
I like the idea, maybe adding those 2 fields in the Home Screen, after the welcome message.
